name = "elnarradorweb2"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "elnarradordemexico.com/*", zone_name = "elnarradordemexico.com" },
  { pattern = "www.elnarradordemexico.com/*", zone_name = "elnarradordemexico.com" },
]

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://fewwvcrfhdgnpfjyadev.supabase.co"
